name: Build and Deploy to GitHub Pages

on:
  push:
    branches: 
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload to GitHub Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Upbeat.apk
          path: app/build/outputs/apk/debug/app-debug.apk